/**
 * /quests/[id] — Quest detail (server component)
 *
 * Supports both:
 * - Legacy quests (status = 'active', proof_type simple)
 * - Business quests (quest_status = 'active'|'published', with tasks/rewards)
 */

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getQuestSharePreview, buildShareDescription } from "@/lib/data/share";
import { getQuestDetail, getBusinessQuestDetail } from "@/lib/data/quests";
import QuestDetailClient from "./QuestDetailClient";
import BusinessQuestDetailClient from "./BusinessQuestDetailClient";
import { SharePreviewLanding } from "@/components/features/share/SharePreviewLanding";

export const dynamic = "force-dynamic";

interface Props { params: Promise<{ id: string }> }

/**
 * Open Graph metadata for the shared link.
 *
 * Built from the public view of the row (see src/lib/data/share.ts), so a
 * challenge the public cannot read falls through to the site-level StrivUp
 * card rather than leaking a title. The og:image itself is generated by
 * opengraph-image.tsx in this folder and attached by Next, which is why no
 * images array appears here.
 */
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const preview = await getQuestSharePreview(id);

  if (!preview) {
    return { title: "Quest" };
  }

  const description = buildShareDescription(preview);
  const url = `/quests/${id}`;

  return {
    title: preview.title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "article",
      siteName: "StrivUp",
      title: preview.title,
      description,
      url,
    },
    twitter: {
      card: "summary_large_image",
      title: preview.title,
      description,
    },
  };
}

export default async function QuestDetailPage({ params }: Props) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  /* Signed out. This route is exempt from the proxy's auth redirect so that
     social crawlers can read its metadata (SHAREABLE_DETAIL in
     src/proxy.ts), so an anonymous visitor reaches this component and is
     shown the public preview rather than the quest itself. */
  if (!user) {
    const preview = await getQuestSharePreview(id);
    return <SharePreviewLanding preview={preview} destination={`/quests/${id}`} />;
  }

  // Try business quest first (has tasks/rewards)
  const bizQuest = await getBusinessQuestDetail(supabase, id);
  if (bizQuest && bizQuest.tasks.length > 0) {
    // The verification prompt greets the user by name, so read it here rather
    // than round-tripping to the browser for it.
    const { data: profile } = await supabase
      .from("profiles")
      .select("full_name, username")
      .eq("id", user.id)
      .maybeSingle();
    const userName = profile?.full_name ?? profile?.username ?? null;

    return (
      <BusinessQuestDetailClient
        quest={bizQuest}
        currentUserId={user.id}
        currentUserName={userName}
      />
    );
  }

  // Fallback to legacy quest
  const quest = await getQuestDetail(supabase, id);
  if (!quest) notFound();

  return <QuestDetailClient quest={quest} currentUserId={user.id} />;
}
