/**
 * app/(app)/challenges/[id]/page.tsx — Challenge Detail server page
 *
 * Fetches all data server-side and passes typed props to ChallengeDetailClient.
 * In Next.js 16, `params` is a Promise and must be awaited.
 *
 * isParticipant = true when the user has a challenge_participants row
 * (joinedAt !== null). This gates the task-list / upload section in the client.
 */

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getChallengeSharePreview, buildShareDescription } from "@/lib/data/share";
import {
  getChallengeDetail,
  getChallengeStats,
  getChallengeLeaderboard,
  getParticipantJoinedAt,
} from "@/lib/data/challenges";
import { getFeedPosts } from "@/lib/data/feed";
import { getChallengeTasks, getUserTaskSubmissions } from "@/lib/data/tasks";
import { ChallengeDetailClient } from "./ChallengeDetailClient";
import { SharePreviewLanding } from "@/components/features/share/SharePreviewLanding";

interface PageProps {
  params: Promise<{ id: string }>;
}

/**
 * Open Graph metadata for the shared link.
 *
 * Built from the public view of the row (see src/lib/data/share.ts), so a
 * challenge the public cannot read falls through to the site-level StrivUp
 * card rather than leaking a title. The og:image itself is generated by
 * opengraph-image.tsx in this folder and attached by Next, which is why no
 * images array appears here.
 */
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const preview = await getChallengeSharePreview(id);

  if (!preview) {
    return { title: "Challenge" };
  }

  const description = buildShareDescription(preview);
  const url = `/challenges/${id}`;

  return {
    title: preview.title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "article",
      siteName: "StrivUp",
      title: preview.title,
      description,
      url,
    },
    twitter: {
      card: "summary_large_image",
      title: preview.title,
      description,
    },
  };
}

export default async function ChallengeDetailPage({ params }: PageProps) {
  const { id } = await params;
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  /* Signed out. The proxy lets this route through without a session so link
     previews can be generated (see SHAREABLE_DETAIL in src/proxy.ts), which
     means the signed-out case has to be handled here rather than assumed
     away. Nothing below this branch runs: the visitor gets the public
     preview card and a way in, and none of the participant data is even
     queried. */
  if (!user) {
    const preview = await getChallengeSharePreview(id);
    return (
      <SharePreviewLanding preview={preview} destination={`/challenges/${id}`} />
    );
  }

  /* One wave, not three. This used to be the six below, then a separate
     query for creator_id, then a third for the viewer's submissions, each
     waiting on the one before it. creator_id now rides along on
     getChallengeDetail, and the submissions query is issued here
     unconditionally: it returns no rows for someone who has not joined, which
     is cheaper than the round trip that was spent finding out whether to ask. */
  const [baseDetail, stats, leaderboard, feed, joinedAt, tasks, submissions] =
    await Promise.all([
      getChallengeDetail(supabase, id),
      getChallengeStats(supabase, id, user.id),
      getChallengeLeaderboard(supabase, id, 3),
      getFeedPosts(supabase, { challengeId: id, limit: 10, viewerId: user.id }),
      getParticipantJoinedAt(supabase, id, user.id),
      getChallengeTasks(supabase, id),
      getUserTaskSubmissions(supabase, id, user.id),
    ]);

  if (!baseDetail) notFound();

  // isParticipant: user has a challenge_participants row for this challenge
  const isParticipant = joinedAt !== null;

  // isCreator gates the invite / manage-tasks / review controls. Resolved here
  // rather than in the client, which previously had no creator id at all and
  // showed those links to every signed-in viewer.
  const isCreator = baseDetail.creatorId === user.id;

  // Held back from a non-participant so the client keeps the shape it had.
  const userSubmissions = isParticipant ? submissions : [];

  // Merge stats into the full ChallengeDetail shape
  const challenge = {
    ...baseDetail,
    activeCount: stats.activeCount,
    memberCount: stats.memberCount,
    successPercent: stats.successPercent,
    currentStreak: stats.currentStreak,
  };

  return (
    <ChallengeDetailClient
      challenge={challenge}
      leaderboard={leaderboard}
      feed={feed}
      userId={user?.id ?? null}
      joinedAt={joinedAt}
      isParticipant={isParticipant}
      isCreator={isCreator}
      tasks={tasks}
      userSubmissions={userSubmissions}
    />
  );
}
